name: core
description: A new Flutter package project.
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  animate_do: ^2.1.0
  cached_network_image: ^3.2.0
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  google_fonts: ^2.2.0
  intl: ^0.17.0
  provider: ^6.0.2
  shimmer: ^2.0.0
  sqflite: ^2.0.1

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17

flutter:
